photostats/directories/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ListAllView.as_view()),
    path('tree', views.tree, name='tree'),
]

photostats/images/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ListAllView.as_view())
]

photostats/importer/urls.py
from django.urls import path

from . import views

app_name = 'importer'
urlpatterns = [
    path('', views.index, name='index'),
    path('action', views.action, name='action'),
]

photostats/photostats/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('importer/', include('importer.urls')),
    path('images/', include('images.urls')),
    path('directories/', include('directories.urls')),
    path('reports/', include('reports.urls')),
]

photostats/reports/urls.py
from django.urls import path

from . import views

app_name = 'reports'
urlpatterns = [
    path('', views.index, name='index'),
    path('timelines', views.timelines, name='timelines'),
    path('compare', views.compare, name='compare'),
]

photostats/directories/models.py
from django.db import models


class Directory(models.Model):

    path = models.CharField(max_length=200, unique=True)
    text = models.CharField(max_length=200, null=True, blank=True)
    parent = models.ForeignKey(
        'self', on_delete=models.SET_NULL, null=True, blank=True)
    selectable = models.BooleanField(default=False)

    @property
    def image_count(self):
        return self.image_set.count()

    def __str__(self):
        if self.text:
            return self.text

        else:
            return self.path

    # fix the fact that djando admin does not allow saving empty strings
    # even though the field is null-able
    def save(self, *args, **kwargs):
        if not self.parent:
            self.parent = None

        if not self.text:
            self.text = None
        super(Directory, self).save(*args, **kwargs)

photostats/images/models.py
from django.db import models
from datetime import datetime
import os

from directories.models import Directory


class Camera(models.Model):
    camera_make = models.CharField(max_length=100, null=True)
    camera_model = models.CharField(max_length=100, null=True)

    class Meta:
        unique_together = ['camera_make', 'camera_model']

    def __str__(self):

        if self.camera_make:
            make = self.camera_make
        else:
            make = '<unknown>'

        if self.camera_model:
            model = self.camera_model
        else:
            model = '<unknown>'

        return (make + ': ' + model)


class Lens(models.Model):
    lens_model = models.CharField(max_length=100, blank=True)

    # does not work due to empty string
    # def __str__(self):
    #     return (self.lens_model)


class Image(models.Model):
    filename = models.CharField(max_length=200)
    date_taken = models.DateTimeField(null=True)

    path = models.ForeignKey(Directory, on_delete=models.CASCADE)
    camera = models.ForeignKey(Camera, on_delete=models.SET_NULL, null=True)
    lens = models.ForeignKey(Lens, on_delete=models.SET_NULL, null=True)

    focal_length = models.PositiveSmallIntegerField(null=True)
    exposure_time = models.FloatField(null=True)
    aperture = models.FloatField(null=True)

    class Meta:
        ordering = ["-filename"]
        unique_together = ['filename', 'path']

    def get_path(self):
        return (os.path.join(self.path.path, self.filename))

    def get_file_type(self):
        name, extension = os.path.splitext(self.get_path())
        return extension

    def __str__(self):
        return str(self.get_path())


def format_datetime(input):
    # 2017:07:04 19:07:42
    # It must be in YYYY-MM-DD HH:MM[:ss
    date = str(input).strip()
    date = str(date[:10])
    elements = date.split(":")
    date = '-'.join(elements)

    time = str(input).strip()
    time = time[11:]

    out = str(date + " " + time)

    # conversion to ensure format is correct
    datetime.strptime(out, '%Y-%m-%d %H:%M%S:%f')

    return out

photostats/importer/models.py
from django.db import models


class Importer(models.Model):
    import_path = models.CharField(max_length=200)

photostats/reports/models.py
from django.db import models

# Create your models here.

photostats/directories/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseServerError

from .models import Directory
from .directoryTreeUi import DirectoryTreeUi


class ListAllView(generic.ListView):
    model = Directory


def tree(request):

    uiTree = DirectoryTreeUi(request)

    return HttpResponse(uiTree.render())

photostats/images/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.views import generic

from .models import Image


class ListAllView(generic.ListView):
    model = Image

photostats/importer/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseServerError
from django.template import loader

from images.models import Image
from directories.models import Directory
from . import ImporterLogic


def index(request):
    # https://docs.djangoproject.com/en/4.0/intro/tutorial04/
    # return HttpResponse("Hello, world. You're at the importer action.")

    # image_list = Image.objects.all()
    template = loader.get_template('importer/index.html')
    context = {}
    return HttpResponse(template.render(context, request))


def action(request):

    # determine button clicked
    try:
        button = get_button(request)

    except ValueError as exc:
        return HttpResponseServerError(str(exc))

    # handle buttons
    if button == 'List':
        return action_list(request)

    elif button == 'Delete':
        return action_delete(request)

    elif button == 'Import':
        return action_import(request)

    else:
        if not button:
            button = '<empty>'

        text = "Button clicked is unknown: " + button
        return HttpResponseServerError(text)


def get_button(request):
    # determine button that was clicked
    button = request.POST.get('list')

    if not button:
        button = request.POST.get('delete')

    if not button:
        button = request.POST.get('import')

    if not button:
        text = 'No button found'
        raise ValueError(text)

    return button


def action_list(request):

    try:
        path = ImporterLogic.validate_path(request.POST.get('Ipath'))

        dir = Directory.objects.get(path=path)

    except Exception as inst:
        text = str(inst)
        return HttpResponseServerError(text)

    else:

        image_list = dir.image_set.all()

        template = loader.get_template('images/image_list.html')
        context = {
            'image_list': image_list
        }
        return HttpResponse(template.render(context, request))


def action_import(request):

    if request.POST.get('recursion') == 'recursion':
        recursive_scan = True
    else:
        recursive_scan = False

    if request.POST.get('scan files') == 'Scan files':
        files_scan = True
    else:
        files_scan = False

    try:
        status_list = ImporterLogic.do_import(
            request.POST.get('Ipath'), recursive_scan, files_scan)

    except Exception as inst:
        text = str(inst)
        return HttpResponseServerError(text)

    else:
        template = loader.get_template('importer/import_status.html')
        context = {
            'import_list': status_list
        }
        return HttpResponse(template.render(context, request))


def action_delete(request):

    try:
        message = ImporterLogic.delete(request.POST.get('Ipath'))

    except Exception as inst:
        text = str(inst)
        return HttpResponseServerError(text)

    else:
        return HttpResponse(message)

photostats/reports/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseServerError
from django.urls.conf import path
from django.template import loader

from .repTimelines import RepTimelines
from .repCompare import RepCompare


def index(request):

    template = loader.get_template('reports/index.html')
    context = {}
    return HttpResponse(template.render(context, request))


def timelines(request):

    try:
        report = RepTimelines(request)

        return report.render()

    except Exception as inst:
        text = str(inst)
        return HttpResponseServerError(text)


def compare(request):

    try:
        report = RepCompare(request)

        return report.render()

    except Exception as inst:
        text = str(inst)
        return HttpResponseServerError(text)

photostats/directories/templates/directories/block_directory_sel.html
{% if Title %}
<legend><h3>{{ Title }}</h3></legend>
{% endif %}
<select class="form-control" id="{{ DivId }}" name='{{ SelectorName }}'>
    {% for dir in dirList %}
        {% if dir.model.pk == Selected %}
            <option value='{{dir.model.pk}}' selected>{{ dir.title }}</option>
        {% else %}
            <option value='{{dir.model.pk}}'>{{ dir.title }}</option>
        {% endif %}
    {% endfor %}
</select>    

photostats/directories/templates/directories/directory_list.html
{% if directory_list %}
    <table>
        <tr>
          <th>ID</th>
          <th>path</th>
          <th>text</th>
          <th>parent</th>
          <th>selectable</th>
          <th>image count</th>
        </tr>
        {% for dir in directory_list %}
        <tr>
          <td><b>{{ dir.pk }}</b></td>
          <td>{{ dir.path }}</td>
          <td>{{ dir.text}}</td>
          <td>{{ dir.parent}}</td>
          <td>{{ dir.selectable}}</td>
          <td>{{ dir.image_count}}</td>
        </tr>
        {% endfor %}
      </table> 

{% else %}
    <p>No directories are available.</p>
{% endif %}

photostats/directories/templates/directories/directory_tree.html
{% if directory_list %}
<div>
    <table>
        <tr>
          <th>ID</th>
          <th>path</th>
          <th>text</th>
          <th>parent</th>
          <th>selectable</th>
          <th>image count</th>
        </tr>
        {% for dir in directory_list %}
        {% autoescape off %}
        {{ dir }}
        {% endautoescape %}
        {% endfor %}
    </table> 
</div>      
<div>
    Here goes the button row (e.g. all selectable, clear all texts)
</div>
{% else %}
    <p>No directories are available.</p>
{% endif %}

photostats/directories/templates/directories/directory_tree_el.html
<tr>
    <td>{{ depth }}</td>
    <td><b>{{ dir.pk }}</b></td>
    <td>{{ dir.path }}</td>
    <td>{{ dir.text}}</td>
    <td>{{ dir.parent}}</td>
    <td>{{ dir.image_count}}</td>
    <td>{{ dir.selectable}}</td>
</tr>

photostats/images/templates/images/image_list.html
{% if image_list %}
    <table>
        <tr>
          <th>filename</th>
          <th>path</th>
          <th>date taken</th>
          <th>Camera make</th>
          <th>Camera model</th>
          <th>Lens model</th>
          <th>Focal length</th>
          <th>Exposure time</th>
          <th>Aperture</th>
        </tr>
        {% for image in image_list %}
        <tr>
          <td><b>{{ image.filename }}</b></td>
          <td>{{ image.path }}</td>
          <td>{{ image.date_taken }}</td>

          <td>{{ image.camera.camera_make }}</td>
          <td>{{ image.camera.camera_model }}</td>
          <td>{{ image.lens.lens_model }}</td>
          <td>{{ image.focal_length }}</td>
          <td>{{ image.exposure_time }}</td>
          <td>{{ image.aperture }}</td>     
        </tr>
        {% endfor %}
      </table> 

{% else %}
    <p>No images are available.</p>
{% endif %}

photostats/importer/templates/importer/import_status.html
{% if import_list %}
<table>
    <tr>
      {% comment %} <th>path</th>
      <th>filename</th> {% endcomment %}
      <th>status</th>
    </tr>
    {% for row in import_list %}
    <tr>
      <td>{{ row }}</td>
      {% comment %} <td>{{ row.path }}</td>
      <td><b>{{ row.filename }}</b></td>
      <td>{{ row.status }}</td>  {% endcomment %}
    </tr>
    {% endfor %}
  </table> 
{% else %}
    <p>No files imported.</p>
{% endif %}

photostats/importer/templates/importer/index.html
<form action="{% url 'importer:action' %}" method="post">
    {% csrf_token %}

    <fieldset>
        <legend><h1>Importer</h1></legend>
        <label for="Ipath">Path</label><br>
        <input type="text" id="Ipath" name="Ipath" value="{{ importer.import_path }}" size="90"><br>
        
        <input type="checkbox" id="cb_recursion" name="recursion" value="recursion" checked>
        <label for="cb_recursion">Scan subfolders</label><br>

        <input type="checkbox" id="cb_scan_files" name="scan files" value="Scan files">
        <label for="cb_san_files">Scan files</label><br>

        {% comment %} <div>
            <input type="radio" id="update" name="radio_upd" value="Update" checked>
            <label for="update">Update</label><br>
            <input type="radio" id="insert" name="radio_upd" value="Insert">
            <label for="insert">Insert</label><br>
        </div> {% endcomment %}

    </fieldset>

    <input type="submit" name="list" value="List">
    <input type="submit" name="delete" value="Delete">
    <input type="submit" name="import" value="Import">
</form>

photostats/reports/templates/reports/blocks/block_figure.html
<div id="{{ div_id }}" class="figure_div">
    {% if Title %}
    <h3>{{ Title }}</h3>
    {% endif %}
    {% autoescape off %}
    {{ Figure }}
    {% endautoescape %}
    {% if Count %}
    <p align="right">#Images: {{ Count }}&nbsp;</p>
    {% endif %}
</div>

photostats/reports/templates/reports/compare.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Photo Statistics</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'reports/photostats.css' %}">
</head>
<body>
  <div id="wrapper">

    <form action="{% url 'reports:compare' %}" method="post">
      {% csrf_token %}    
      <fieldset>      
      <div id="left_top" class="rep_column_left">
        {% autoescape off %}
            {{ FilterLeft }}
        {% endautoescape %}
      </div>      
      <div id="right_top" class="rep_column_right">
        {% autoescape off %}
            {{ FilterRight }}
        {% endautoescape %}
      </div>
      <div id="joint">      
        <input type="submit" name="search" value="Search">
      </div>
    </fieldset>
    </form>    
    <div id="left_main" class="rep_column_left">
        {% autoescape off %}
            {{ FocalLengthDonutLeft_div }}
        {% endautoescape %}
    </div>
    <div id="right_main" class="rep_column_right">
        {% autoescape off %}
            {{ FocalLengthDonutRight_div }}
        {% endautoescape %}
    </div>    
  </div>
</body>
</html>

photostats/reports/templates/reports/index.html
<!DOCTYPE html>
<html>
   <head>
      <title>PhotoStats reporting overview</title>
   </head>
   <body>
       <h1>All my reports</h1>
    <ul>
        <li><a href="/reports/timelines">Timelines</a></li>
        <li><a href="/reports/compare">Compare folders</a></li>
    </ul> 
   </body>
</html>

photostats/reports/templates/reports/timelines.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Photo Statistics</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'reports/photostats.css' %}">
</head>
<body>
  <div>

    <div id="filter" class="container">
      <form action="{% url 'reports:timelines' %}" method="get">
          {% csrf_token %}

          <fieldset>
            {% autoescape off %}
            {{ DirectoryFilter }}
            {% endautoescape %}
          </fieldset>
          <input type="submit" name="search" value="Search">
      </form>
    </div>

    <div id="main" class="container">
      {% autoescape off %}
      {{ FocalLengthDonut_div }}
      {% endautoescape %}

      {% autoescape off %}
      {{ CamerasOverTime_div }}
      {% endautoescape %}

      {% autoescape off %}
      {{ MobileVsCamRatio_div }}
      {% endautoescape %}
      
    </div>

  </div>
</body>
</html>